[package]
name = "languagetool-zed-extension"
version = "0.2.1"
edition = "2021"
authors = ["Maxim Schuwalow"]
description = "LanguageTool integration for Zed."
license = "MIT"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "<1"

[profile.release]
lto = "thin"
